services:
  db:
    image: postgres:15-alpine
    container_name: wallet_app_db
    restart: always
    volumes:
      - ./mount/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
