# Generated by Django 5.1.6 on 2025-02-14 20:03

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txid",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet_app.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["txid"], name="wallet_app__txid_9b4da0_btree"
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["wallet"], name="wallet_app__wallet__7231fe_btree"
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["created_at"], name="wallet_app__created_606f1c_btree"
                    ),
                ],
            },
        ),
    ]
